### ISSUE TITLE
Error code : SE message: 抱歉，閒置逾時。請重新登入。(Solved)

### ISSUE THREAD

**Issue by waynetse1102** [thematrixdev/home-assistant-clp#6]
Could you please help to solve the error.
![002](https://github.com/thematrixdev/home-assistant-clp/assets/43468677/084939f0-8311-4f9a-8295-21b8733cb31c)
![001](https://github.com/thematrixdev/home-assistant-clp/assets/43468677/4ec2344b-341e-4f54-b436-cb196fe32574)

**Comment by bunny19890131** [comment]
一开始我一直以为是30s的设置问题，改到了3000都不行，后来发线账单那个账号填错了，改正就有数据了。。你检查下
