### ISSUE TITLE
User agent is old and needs updating

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [thematrixdev/home-assistant-clp#8]
Same as title

**Comment by thematrixdev** [comment]
Does it affect the functionality?

**Comment by SodaWithoutSparkles** [comment]
It shouldn't affect functionally. But I've cherry-picked the modifications onto my HA instance. Will report in a few hours.

**Comment by SodaWithoutSparkles** [comment]
doesnt seem to have any side effects
